In [1]:
import numpy as np
a = np.array([[1,0,0],[0,2,0],[0,0,1]],dtype = int)
b = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = int)

In [2]:
a.shape # dimension

(3, 3)

In [3]:
a.size # elements

9

In [4]:
c = np.matmul(a,b)  # left product, row operation
c

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [ 7,  8,  9]])

In [5]:
d = np.matmul(b,a) # right procuct, column operation
d

array([[ 1,  4,  3],
       [ 4, 10,  6],
       [ 7, 16,  9]])

![sp190222_102845.png](https://i.loli.net/2019/02/22/5c6f5e6c38b31.png)

In [11]:
e = np.array([[0,0,1],[0,1,0],[1,0,0]],dtype = int) # assuming b is an image, b * e to flip image
f = np.matmul(b,e)
f

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])